-- MySQL Script generated by MySQL Workbench
-- 01/10/17 17:29:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema roule_ma_poule
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `roule_ma_poule` ;

-- -----------------------------------------------------
-- Schema roule_ma_poule
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `roule_ma_poule` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `roule_ma_poule` ;

-- -----------------------------------------------------
-- Table `roule_ma_poule`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roule_ma_poule`.`utilisateur` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `roule_ma_poule`.`utilisateur` (
  `utilisateur_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `utilisateur_pseudo` VARCHAR(30) NOT NULL,
  `utilisateur_nom` VARCHAR(45) NOT NULL,
  `utilisateur_prenom` VARCHAR(45) NOT NULL,
  `utilisateur_portable` INT NOT NULL,
  `utilisateur_score` INT NOT NULL DEFAULT 0,
  `utilisateur_points_fidelite` INT NOT NULL DEFAULT 0,
  `utilisateur_date_naissance` DATETIME NOT NULL,
  `utilisateur_mot_de_passe` VARCHAR(60) NOT NULL,
  `utilisateur_date_creation` DATETIME NOT NULL,
  `utilisateur_date_modification` DATETIME NOT NULL,
  `utilisateur_date_derniere_connexion` DATETIME NOT NULL,
  `utilisateur_token` VARCHAR(45) NULL,
  PRIMARY KEY (`utilisateur_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `utilisateur_id_UNIQUE` ON `roule_ma_poule`.`utilisateur` (`utilisateur_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `utilisateur_pseudo_UNIQUE` ON `roule_ma_poule`.`utilisateur` (`utilisateur_pseudo` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `roule_ma_poule`.`trajet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roule_ma_poule`.`trajet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `roule_ma_poule`.`trajet` (
  `trajet_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trajet_longitude_depart` DOUBLE NOT NULL,
  `trajet_latitude_depart` DOUBLE NOT NULL,
  `trajet_longitude_arrivee` DOUBLE NOT NULL,
  `trajet_latitude_arrivee` DOUBLE NOT NULL,
  `trajet_public` TINYINT(1) NOT NULL,
  `utilisateur_utilisateur_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`trajet_id`, `utilisateur_utilisateur_id`),
  CONSTRAINT `fk_Trajet_Utilisateur1`
    FOREIGN KEY (`utilisateur_utilisateur_id`)
    REFERENCES `roule_ma_poule`.`utilisateur` (`utilisateur_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `trajet_id_UNIQUE` ON `roule_ma_poule`.`trajet` (`trajet_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Trajet_Utilisateur1_idx` ON `roule_ma_poule`.`trajet` (`utilisateur_utilisateur_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `utilisateur_utilisateur_id_UNIQUE` ON `roule_ma_poule`.`trajet` (`utilisateur_utilisateur_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `roule_ma_poule`.`evenement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roule_ma_poule`.`evenement` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `roule_ma_poule`.`evenement` (
  `evenement_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `evenement_nom` VARCHAR(45) NOT NULL,
  `evenement_descriptif` VARCHAR(200) NULL,
  `evenement_ville` VARCHAR(45) NOT NULL,
  `evenement_longitude` DOUBLE NOT NULL,
  `evenement_latitude` DOUBLE NOT NULL,
  `evenement_dateheure` DATETIME NOT NULL,
  PRIMARY KEY (`evenement_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `evenement_id_UNIQUE` ON `roule_ma_poule`.`evenement` (`evenement_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `roule_ma_poule`.`utilisateur_evenement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roule_ma_poule`.`utilisateur_evenement` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `roule_ma_poule`.`utilisateur_evenement` (
  `utilisateur_evenement_utilisateur_id` INT UNSIGNED NULL,
  `utilisateur_evenement_evenement_id` INT UNSIGNED NULL,
  `utilisateur_evenement_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`utilisateur_evenement_id`),
  CONSTRAINT `fk_Utilisateur_has_Evenement_Utilisateur`
    FOREIGN KEY (`utilisateur_evenement_utilisateur_id`)
    REFERENCES `roule_ma_poule`.`utilisateur` (`utilisateur_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Evenement_Evenement1`
    FOREIGN KEY (`utilisateur_evenement_evenement_id`)
    REFERENCES `roule_ma_poule`.`evenement` (`evenement_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Utilisateur_has_Evenement_Evenement1_idx` ON `roule_ma_poule`.`utilisateur_evenement` (`utilisateur_evenement_evenement_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Utilisateur_has_Evenement_Utilisateur_idx` ON `roule_ma_poule`.`utilisateur_evenement` (`utilisateur_evenement_utilisateur_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `Utilisateur_Evenement_id_UNIQUE` ON `roule_ma_poule`.`utilisateur_evenement` (`utilisateur_evenement_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
